version: '2'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
      stdin_open: "true"
      tty: "true"
    ports:
         - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      stdin_open: "true"
      tty: "true"

  web:
      image: httpd
      ports:
        - "8082:80"
      stdin_open: "true"
      tty: "true"
      volumes:
         - /root/myapp:/usr/local/apache2/htdocs
